
#!/usr/bin/env bash
# scripts/qwen-run.sh
set -euo pipefail

FEATURE_MD="${1:?Uso: qwen-run.sh playbooks/<feature>.md}"
FEATURE_SLUG=$(basename "$FEATURE_MD" .md)

git checkout -B "feat/${FEATURE_SLUG}"

PROMPT_TMP=".tmp/prompt-${FEATURE_SLUG}.md"
mkdir -p .tmp artifacts

./scripts/assemble-context.sh "$FEATURE_MD" "$PROMPT_TMP"

# Llamada a LLXPRT/Qwen (ajusta 'llxprt' al binario real en tu entorno)
: "${QWEN_MODEL:=qwen2.5-coder-32b}"
llxprt run qwen --model "$QWEN_MODEL" --input "$PROMPT_TMP" --out "artifacts/${FEATURE_SLUG}" || true

# Aplicar cambios si se generó un patch, o copiar archivos
if [ -f "artifacts/${FEATURE_SLUG}/diff.patch" ]; then
  git apply "artifacts/${FEATURE_SLUG}/diff.patch"
elif [ -d "artifacts/${FEATURE_SLUG}" ]; then
  rsync -a "artifacts/${FEATURE_SLUG}/" ./ || true
fi

git add -A
git commit -m "feat(${FEATURE_SLUG}): generated by Qwen (LLXPRT)" || true
